#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum RrType {
    None,
    A,
    NS,
    MD,
    MF,
    CNAME,
    SOA,
    MB,
    MG,
    MR,
    Null,
    PTR,
    HINFO,
    MINFO,
    MX,
    TXT,
    RP,
    AFSDB,
    X25,
    ISDN,
    RT,
    NSAPPTR,
    SIG,
    KEY,
    PX,
    GPOS,
    AAAA,
    LOC,
    NXT,
    EID,
    NIMLOC,
    SRV,
    ATMA,
    NAPTR,
    KX,
    CERT,
    DNAME,
    OPT,
    APL,
    DS,
    SSHFP,
    IPSECKEY,
    RRSIG,
    NSEC,
    DNSKEY,
    DHCID,
    NSEC3,
    NSEC3PARAM,
    TLSA,
    SMIMEA,
    HIP,
    NINFO,
    RKEY,
    TALINK,
    CDS,
    CDNSKEY,
    OPENPGPKEY,
    CSYNC,
    ZONEMD,
    SVCB,
    HTTPS,
    SPF,
    UINFO,
    UID,
    GID,
    UNSPEC,
    NID,
    L32,
    L64,
    LP,
    EUI48,
    EUI64,
    NXNAME,
    URI,
    CAA,
    AVC,
    AMTRELAY,
    RESINFO,
    TKEY,
    TSIG,
    IXFR,
    AXFR,
    MAILB,
    MAILA,
    ANY,
    TA,
    DLV,
    Reserved,
    Unknown(u16),
}

#[allow(dead_code)]
impl RrType {
    pub(crate) fn from_u16(code: u16) -> Self {
        match code {
            0 => Self::None,
            1 => Self::A,
            2 => Self::NS,
            3 => Self::MD,
            4 => Self::MF,
            5 => Self::CNAME,
            6 => Self::SOA,
            7 => Self::MB,
            8 => Self::MG,
            9 => Self::MR,
            10 => Self::Null,
            12 => Self::PTR,
            13 => Self::HINFO,
            14 => Self::MINFO,
            15 => Self::MX,
            16 => Self::TXT,
            17 => Self::RP,
            18 => Self::AFSDB,
            19 => Self::X25,
            20 => Self::ISDN,
            21 => Self::RT,
            23 => Self::NSAPPTR,
            24 => Self::SIG,
            25 => Self::KEY,
            26 => Self::PX,
            27 => Self::GPOS,
            28 => Self::AAAA,
            29 => Self::LOC,
            30 => Self::NXT,
            31 => Self::EID,
            32 => Self::NIMLOC,
            33 => Self::SRV,
            34 => Self::ATMA,
            35 => Self::NAPTR,
            36 => Self::KX,
            37 => Self::CERT,
            39 => Self::DNAME,
            41 => Self::OPT,
            42 => Self::APL,
            43 => Self::DS,
            44 => Self::SSHFP,
            45 => Self::IPSECKEY,
            46 => Self::RRSIG,
            47 => Self::NSEC,
            48 => Self::DNSKEY,
            49 => Self::DHCID,
            50 => Self::NSEC3,
            51 => Self::NSEC3PARAM,
            52 => Self::TLSA,
            53 => Self::SMIMEA,
            55 => Self::HIP,
            56 => Self::NINFO,
            57 => Self::RKEY,
            58 => Self::TALINK,
            59 => Self::CDS,
            60 => Self::CDNSKEY,
            61 => Self::OPENPGPKEY,
            62 => Self::CSYNC,
            63 => Self::ZONEMD,
            64 => Self::SVCB,
            65 => Self::HTTPS,
            99 => Self::SPF,
            100 => Self::UINFO,
            101 => Self::UID,
            102 => Self::GID,
            103 => Self::UNSPEC,
            104 => Self::NID,
            105 => Self::L32,
            106 => Self::L64,
            107 => Self::LP,
            108 => Self::EUI48,
            109 => Self::EUI64,
            128 => Self::NXNAME,
            249 => Self::TKEY,
            250 => Self::TSIG,
            251 => Self::IXFR,
            252 => Self::AXFR,
            253 => Self::MAILB,
            254 => Self::MAILA,
            255 => Self::ANY,
            256 => Self::URI,
            257 => Self::CAA,
            258 => Self::AVC,
            260 => Self::AMTRELAY,
            261 => Self::RESINFO,
            32768 => Self::TA,
            32769 => Self::DLV,
            65535 => Self::Reserved,
            _ => Self::Unknown(code),
        }
    }

    pub(crate) fn to_u16(self) -> u16 {
        match self {
            Self::None => 0,
            Self::A => 1,
            Self::NS => 2,
            Self::MD => 3,
            Self::MF => 4,
            Self::CNAME => 5,
            Self::SOA => 6,
            Self::MB => 7,
            Self::MG => 8,
            Self::MR => 9,
            Self::Null => 10,
            Self::PTR => 12,
            Self::HINFO => 13,
            Self::MINFO => 14,
            Self::MX => 15,
            Self::TXT => 16,
            Self::RP => 17,
            Self::AFSDB => 18,
            Self::X25 => 19,
            Self::ISDN => 20,
            Self::RT => 21,
            Self::NSAPPTR => 23,
            Self::SIG => 24,
            Self::KEY => 25,
            Self::PX => 26,
            Self::GPOS => 27,
            Self::AAAA => 28,
            Self::LOC => 29,
            Self::NXT => 30,
            Self::EID => 31,
            Self::NIMLOC => 32,
            Self::SRV => 33,
            Self::ATMA => 34,
            Self::NAPTR => 35,
            Self::KX => 36,
            Self::CERT => 37,
            Self::DNAME => 39,
            Self::OPT => 41,
            Self::APL => 42,
            Self::DS => 43,
            Self::SSHFP => 44,
            Self::IPSECKEY => 45,
            Self::RRSIG => 46,
            Self::NSEC => 47,
            Self::DNSKEY => 48,
            Self::DHCID => 49,
            Self::NSEC3 => 50,
            Self::NSEC3PARAM => 51,
            Self::TLSA => 52,
            Self::SMIMEA => 53,
            Self::HIP => 55,
            Self::NINFO => 56,
            Self::RKEY => 57,
            Self::TALINK => 58,
            Self::CDS => 59,
            Self::CDNSKEY => 60,
            Self::OPENPGPKEY => 61,
            Self::CSYNC => 62,
            Self::ZONEMD => 63,
            Self::SVCB => 64,
            Self::HTTPS => 65,
            Self::SPF => 99,
            Self::UINFO => 100,
            Self::UID => 101,
            Self::GID => 102,
            Self::UNSPEC => 103,
            Self::NID => 104,
            Self::L32 => 105,
            Self::L64 => 106,
            Self::LP => 107,
            Self::EUI48 => 108,
            Self::EUI64 => 109,
            Self::NXNAME => 128,
            Self::TKEY => 249,
            Self::TSIG => 250,
            Self::IXFR => 251,
            Self::AXFR => 252,
            Self::MAILB => 253,
            Self::MAILA => 254,
            Self::ANY => 255,
            Self::URI => 256,
            Self::CAA => 257,
            Self::AVC => 258,
            Self::AMTRELAY => 260,
            Self::RESINFO => 261,
            Self::TA => 32768,
            Self::DLV => 32769,
            Self::Reserved => 65535,
            Self::Unknown(code) => code,
        }
    }
}
